#!/bin/bash

set -e

#
# Configuration
#

# [meta]
export INF_META_HOSTNAME=${INF_META_HOSTNAME:-"localhost"}
export INF_META_BIND_ADDRESS=${INF_META_BIND_ADDRESS:-":8088"}
export INF_META_RETENTION_AUTOCREATE=${INF_META_RETENTION_AUTOCREATE:-true}
export INF_META_ELECTION_TIMEOUT=${INF_META_ELECTION_TIMEOUT:-"1s"}
export INF_META_HEARTBEAT_TIMEOUT=${INF_META_HEARTBEAT_TIMEOUT:-"1s"}
export INF_META_LEADER_LEASE_TIMEOUT=${INF_META_LEADER_LEASE_TIMEOUT:-"500ms"}
export INF_META_COMMIT_TIMEOUT=${INF_META_COMMIT_TIMEOUT:-"50ms"}

# [data]
export INF_DATA_MAX_WAL_SIZE=${INF_DATA_MAX_WAL_SIZE:-104857600}
export INF_DATA_WAL_FLUSH_INTERVAL=${INF_DATA_WAL_FLUSH_INTERVAL:-"10m"}
export INF_DATA_WAL_PARTITION_FLUSH_DELAY=${INF_DATA_WAL_PARTITION_FLUSH_DELAY:-"2s"}

# [cluster]
export INF_CLUSTER_SHARD_WRITER_TIMEOUT=${INF_CLUSTER_SHARD_WRITER_TIMEOUT:-"5s"}
export INF_CLUSTER_WRITE_TIMEOUT=${INF_CLUSTER_WRITE_TIMEOUT:-"5s"}

# [retention]
export INF_RETENTION_ENABLED=${INF_RETENTION_ENABLED:-true}
export INF_RETENTION_CHECK_INTERVAL=${INF_RETENTION_CHECK_INTERVAL:-"10m"}

# [admin]
export INF_ADMIN_ENABLED=${INF_ADMIN_ENABLED:-true}
export INF_ADMIN_BIND_ADDRESS=${INF_ADMIN_BIND_ADDRESS:-":8083"}

# [http]
export INF_HTTP_ENABLED=${INF_HTTP_ENABLED:-true}
export INF_HTTP_BIND_ADDRESS=${INF_HTTP_BIND_ADDRESS:-":8086"}
export INF_HTTP_AUTH_ENABLED=${INF_HTTP_AUTH_ENABLED:-true}
export INF_HTTP_LOG_ENABLED=${INF_HTTP_LOG_ENABLED:-true}
export INF_HTTP_WRITE_TRACING=${INF_HTTP_WRITE_TRACING:-false}
export INF_HTTP_PPROF_ENABED=${INF_HTTP_PPROF_ENABED:-false}

# [graphite]
export INF_GRAPHITE_ENABLED=${INF_GRAPHITE_ENABLED:-false}
export INF_GRAPHITE_BIND_ADDRESS=${INF_GRAPHITE_BIND_ADDRESS:-":2003"}
export INF_GRAPHITE_PROTOCOL=${INF_GRAPHITE_PROTOCOL:-"tcp"}
export INF_GRAPHITE_CONSISTENCY_LEVEL=${INF_GRAPHITE_CONSISTENCY_LEVEL:-"one"}
export INF_GRAPHITE_NAME_SEPARATOR=${INF_GRAPHITE_NAME_SEPARATOR:-"."}
export INF_GRAPHITE_NAME_SCHEMA=${INF_GRAPHITE_NAME_SCHEMA:-"type.host.measurement.device"}
export INF_GRAPHITE_IGNORE_UNNAMED=${INF_GRAPHITE_IGNORE_UNNAMED:-true}

# [collectd]
export INF_COLLECTD_ENABLED=${INF_COLLECTD_ENABLED:-false}
export INF_COLLECTD_BIND_ADDRESS=${INF_COLLECTD_BIND_ADDRESS:-":25827"}
export INF_COLLECTD_DATABASE=${INF_COLLECTD_DATABASE:-"collectd"}
export INF_COLLECTD_TYPESDB=${INF_COLLECTD_TYPESDB:-"/usr/share/collectd/types.db"}

# [openttsdb]
export INF_OPENTSDB_ENABLED=${INF_OPENTSDB_ENABLED:-false}
export INF_OPENTSDB_BIND_ADDRESS=${INF_OPENTSDB_BIND_ADDRESS:-":4711"}
export INF_OPENTSDB_DATABASE=${INF_OPENTSDB_DATABASE:-"opentsdb"}
export INF_OPENTSDB_RETENTION_POLICY=${INF_OPENTSDB_RETENTION_POLICY:-"default"}

# [udp]
export INF_UDP_ENABLED=${INF_UDP_ENABLED:-false}
export INF_UDP_BIND_ADDRESS=${INF_UDP_BIND_ADDRESS:-":4444"}
export INF_UDP_DATABASE=${INF_UDP_DATABASE:-"udp"}
export INF_UDP_BATCH_SIZE=${INF_UDP_BATCH_SIZE:-0}
export INF_UDP_BATCH_TIMEOUT=${INF_UDP_BATCH_TIMEOUT:-"0"}

# [monitoring]
export INF_MONITORING_ENABLED=${INF_MONITORING_ENABLED:-true}
export INF_MONITORING_WRITE_INTERVAL=${INF_MONITORING_WRITE_INTERVAL:-"24h"}

# [continnuous_queries]
export INF_CONTINUOUS_QUERIES_ENABLED=${INF_CONTINUOUS_QUERIES_ENABLED:-true}
export INF_CONTINUOUS_QUERIES_RECOMPUTE_PREVIOUS_N=${INF_CONTINUOUS_QUERIES_RECOMPUTE_PREVIOUS_N:-2}
export INF_CONTINUOUS_QUERIES_RECOMPUTE_NO_OLDER_THAN=${INF_CONTINUOUS_QUERIES_RECOMPUTE_NO_OLDER_THAN:-"10m"}
export INF_CONTINUOUS_QUERIES_COMPUTE_RUNS_PER_INTERVAL=${INF_CONTINUOUS_QUERIES_COMPUTE_RUNS_PER_INTERVAL:-10}
export INF_CONTINUOUS_QUERIES_COMPUTE_NO_MORE_THAN=${INF_CONTINUOUS_QUERIES_COMPUTE_NO_MORE_THAN:-"2m"}

# [hinted-handoff]
export INF_HINTED_HANDOFF_ENABLED=${INF_HINTED_HANDOFF_ENABLED:-true}
export INF_HINTED_HANDOFF_MAX_SIZE=${INF_HINTED_HANDOFF_MAX_SIZE:-1073741824}
export INF_HINTED_HANDOFF_MAX_AGE=${INF_HINTED_HANDOFF_MAX_AGE:-"168h"}
export INF_HINTED_HANDOFF_RETRY_RATE_LIMIT=${INF_HINTED_HANDOFF_RETRY_RATE_LIMIT:-0}
export INF_HINTED_HANDOFF_RETRY_INTERVAL=${INF_HINTED_HANDOFF_RETRY_INTERVAL:-"1s"}


# Prepare configuration file
config=/etc/influxdb/config.toml

echo "Resolving placeholders in configuration file: $config"

perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' $config

# Start server as unprivileged user
gosu influxdb:influxdb \
     /opt/influxdb/influxd \
     -config $config \
     -pidfile /var/run/influxdb/influxdb.pid
